#!/bin/bash
MYEDITOR='open -a /Applications/TextMate.app'
SEARCHING=$(which kpsewhich)
FILES=$@
echo
echo =========STARTING=========
if [ $# -eq 0 ] 
 then
  echo
  echo No file given
  echo usage: gedtex filename [ filename filename ... ]
  echo
  echo ===========DONE===========
else
  for entry in $FILES
   do
	if [ -z "$($SEARCHING $entry)" ]
	 then
 		echo
		echo -e "\033[0;31m No file $entry \033[0m"
	 else
		$MYEDITOR $($SEARCHING $entry) 
 		echo
		echo -e "\033[0;32m Open file $entry \033[0m"
	fi
  done
  echo
  echo ===========DONE===========
fi

