#!/bin/bash
# small script to use the newest svn-version of LaTeX3
echo "Install LaTeX3"
cd $HOME
mkdir tmpinstallfolder-latex3
cd tmpinstallfolder-latex3
svn co http://www.latex-project.org/svnroot/experimental/trunk/
cd trunk
make localinstall
cd $HOME
rmdir --ignore-fail-on-non-empty tmpinstallfolder-latex3
